<?php

use Illuminate\Database\Seeder;

class EmpresasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$data = array (
			array('orden'=>0, 'razon_social'=>'Cliqué Peluquería', 'nombre_comercial'=>'Cliqué Peluquería', 'categoria_id'=>1, 'beneficio'=>'GRATIS manicure', 'direccion'=>'Vía Samborondón C.C. Las Terrazas Local #18 y #19', 'telefono'=>'(04)283-8942', 'correo'=>'', 'twitter'=>'@PeluClique_Gye', 'facebook'=>'Cliqué Peluquería', 'instagram'=>'peluqueriaclique', 'website'=>'www.cliquepeluqueria.com', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Scienza Body Care', 'nombre_comercial'=>'Scienza Body Care', 'categoria_id'=>1, 'beneficio'=>'GRATIS hidratación facial de oro', 'direccion'=>'Victor Emilio Estrada # 722 y Guayacanes', 'telefono'=>'(04)503-7923', 'correo'=>'', 'twitter'=>'@scienzabodycare', 'facebook'=>'Scienza Body Care', 'instagram'=>'scienzabodycare', 'website'=>'www.scienzabodycare.wixsite.com/scienzabodycare', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Skin Care', 'nombre_comercial'=>'Skin Care', 'categoria_id'=>1, 'beneficio'=>'50% Descuento en diagnóstico', 'direccion'=>'Kennedy Norte Av. Luis Orrantia y Nahim Isaías, Torre Médica Udimef 2', 'telefono'=>'(04)268-1880', 'correo'=>'', 'twitter'=>'@SkinCareEC', 'facebook'=>'Skin Care', 'instagram'=>'deniselebedskincare', 'website'=>'www.deniselebedskincareclinic.webnode.com.co', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Tic Toc Tijeras', 'nombre_comercial'=>'Tic Toc Tijeras', 'categoria_id'=>1, 'beneficio'=>'10% Descuento en servicios y productos ', 'direccion'=>'Km 2.5 Vía a Samborondón CC Plaza Nova 2do Piso Local 5', 'telefono'=>'(04) 283-8787', 'correo'=>'', 'twitter'=>'_', 'facebook'=>'Tic Toc Tijeras', 'instagram'=>'tictoctijeras', 'website'=>'www.tictoctijeras.com', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'El Refugio del Cangrejo', 'nombre_comercial'=>'El Refugio del Cangrejo', 'categoria_id'=>2, 'beneficio'=>'12% Descuento en cualquier plato', 'direccion'=>'Palmora Plaza Km 18 vía Samborondón', 'telefono'=>'(04) 207-0798', 'correo'=>'', 'twitter'=>'_', 'facebook'=>'El Refugio del Cangrejo', 'instagram'=>'refugiocangrejo', 'website'=>'_', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Fanáticos', 'nombre_comercial'=>'Fanáticos', 'categoria_id'=>2, 'beneficio'=>'10% Descuento en efectivo', 'direccion'=>'Urdesa Victor Emilio Estrada junto al Bco. Bolivariano ', 'telefono'=>'098 667 0769', 'correo'=>'', 'twitter'=>'@FanaticosSG', 'facebook'=>'Fanáticos', 'instagram'=>'fanaticossg', 'website'=>'www.fanaticos.com.ec', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Master Pizza', 'nombre_comercial'=>'Master Pizza', 'categoria_id'=>2, 'beneficio'=>'GRATIS 2 ingredientes adicionales', 'direccion'=>'Urdesa, Av las monjas 217 y calle 3ra', 'telefono'=>'(04) 238-2888', 'correo'=>'', 'twitter'=>'@MasterPizzaEc', 'facebook'=>'Master Pizza', 'instagram'=>'masterpizza_ec', 'website'=>'www.masterpizza.ec/', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'PizzAdicta', 'nombre_comercial'=>'PizzAdicta', 'categoria_id'=>2, 'beneficio'=>'2 Pizzas familiares por $19.99', 'direccion'=>'Victor Emilio Estrada 823 e Higueras', 'telefono'=>'(04) 601-2794', 'correo'=>'', 'twitter'=>'@MrDicto', 'facebook'=>'PizzAdicta', 'instagram'=>'pizzadictaec', 'website'=>'_', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Caramel Coffee', 'nombre_comercial'=>'Caramel Coffee', 'categoria_id'=>2, 'beneficio'=>'', 'direccion'=>'Vía Samborondón, Km. 2,5 Universidad de Especialidades Espíritu Santo', 'telefono'=>'(04) 259-7060', 'correo'=>'', 'twitter'=>'_', 'facebook'=>'', 'instagram'=>'caramelcoffee_ec', 'website'=>'www.caramelcoffee.com.ec', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Puerto Moro', 'nombre_comercial'=>'Puerto Moro', 'categoria_id'=>2, 'beneficio'=>'Postre GRATIS en cada compra', 'direccion'=>'Urdesa, Circunvalación 320 y Diagonal esquina', 'telefono'=>'(04) 288-4630', 'correo'=>'', 'twitter'=>'@Puertomoro', 'facebook'=>'Puerto Moro', 'instagram'=>'puertomoro', 'website'=>'www.puertomoro.com/', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Segundo Muelle', 'nombre_comercial'=>'Segundo Muelle', 'categoria_id'=>2, 'beneficio'=>'Postre y bebidas GRATIS para cumpleañeros', 'direccion'=>'Centro Comercial San Marino, Piso 1 Local 1', 'telefono'=>'097 960 7632', 'correo'=>'', 'twitter'=>'@SegundoMuelleGy', 'facebook'=>'Segundo Muelle', 'instagram'=>'segundomuellegye', 'website'=>'www.segundomuelle.com/ecuador/reservas-gye', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Úrsula', 'nombre_comercial'=>'Úrsula', 'categoria_id'=>3, 'beneficio'=>'', 'direccion'=>'Centro Comercial Mall Del Sol, Piso 1', 'telefono'=>'098 961 6553', 'correo'=>'', 'twitter'=>'@ursula_ec', 'facebook'=>'Úrsula', 'instagram'=>'ursula_ec', 'website'=>'www.ursula.com.ec', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'L. Gilbert', 'nombre_comercial'=>'L. Gilbert', 'categoria_id'=>3, 'beneficio'=>'20% Descuento en toda la mercadería', 'direccion'=>'Centro Comercial City Mall, Piso 1', 'telefono'=>'097 879 4022', 'correo'=>'', 'twitter'=>'@LGilbertEc', 'facebook'=>'L. Gilbert', 'instagram'=>'lgilbertshoes', 'website'=>'www.l-gilbert.com/', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Huellas', 'nombre_comercial'=>'Huellas', 'categoria_id'=>6, 'beneficio'=>'', 'direccion'=>'Servicio Online a Domicilio', 'telefono'=>'(04) 228-7453', 'correo'=>'floreriahuellas@gmail.com', 'twitter'=>'_', 'facebook'=>'_', 'instagram'=>'_', 'website'=>'www.floreriahuellas.com', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Sweet Expressions', 'nombre_comercial'=>'Sweet Expressions', 'categoria_id'=>3, 'beneficio'=>'10% Descuento en compras y cursos', 'direccion'=>'Calle Bálsamos Sur #201 A, entre calle Única y Todos los Santos', 'telefono'=>'(04) 288-2785', 'correo'=>'', 'twitter'=>'@sweetexprec', 'facebook'=>'Sweet Expressions', 'instagram'=>'', 'website'=>'www.sweetexpressionsec.com/', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Driving Range', 'nombre_comercial'=>'Driving Range', 'categoria_id'=>4, 'beneficio'=>'1 clase de golf de cortesía', 'direccion'=>'Km 6,5 Vía a Samborondón frente a Plaza Lagos', 'telefono'=>'099 950 0682', 'correo'=>'', 'twitter'=>'@drivingrange_ec', 'facebook'=>'Driving Range', 'instagram'=>'drivingrange', 'website'=>'www.drivingrange.com.ec', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'GeekDom', 'nombre_comercial'=>'GeekDom', 'categoria_id'=>4, 'beneficio'=>'', 'direccion'=>'Centro Comercial Las Terrazas, Local 2', 'telefono'=>'099 909 2359', 'correo'=>'', 'twitter'=>'@Geekdomec', 'facebook'=>'Geekdom', 'instagram'=>'geekdomec', 'website'=>'_', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Escapology', 'nombre_comercial'=>'Escapology', 'categoria_id'=>4, 'beneficio'=>'40% Descuento en juegos para 6 personas', 'direccion'=>'Aventura Plaza, Local 17, Av Las Monjas', 'telefono'=>' (04) 220-0101', 'correo'=>'', 'twitter'=>'@EscapologyGYE', 'facebook'=>'Escapology', 'instagram'=>'escapologygye', 'website'=>'www.escapology.com/es/guayaquil', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Teatro Sánchez Aguilar', 'nombre_comercial'=>'Teatro Sánchez Aguilar', 'categoria_id'=>4, 'beneficio'=>'', 'direccion'=>'Av Rio Esmeraldas, Samborondón', 'telefono'=>'(04) 209-7447', 'correo'=>'', 'twitter'=>'@TeatroSanchezA', 'facebook'=>'Teatro Sánchez Aguilar', 'instagram'=>'teatrosancheza', 'website'=>'www.teatrosanchezaguilar.org', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Crossfitculture', 'nombre_comercial'=>'Crossfitculture', 'categoria_id'=>5, 'beneficio'=>'Matrícula GRATIS + 3 meses de regalo', 'direccion'=>'Av. Samborondón Km. 2.5 frente a Plaza Nova', 'telefono'=>'(04) 209-7078', 'correo'=>'', 'twitter'=>'@cfCULTURE', 'facebook'=>'Crossfitculture', 'instagram'=>'crossfitculture', 'website'=>'www.crossfitculture.ec', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Gamboa Boxing', 'nombre_comercial'=>'Gamboa Boxing', 'categoria_id'=>5, 'beneficio'=>'Por 2 meses de entrenamiento recibe 3', 'direccion'=>'Urdenor 1, Mz 130 solares 12 y 13 Av. Francisco de Orellana', 'telefono'=>'(04) 600-8955', 'correo'=>'', 'twitter'=>'@gamboaboxing', 'facebook'=>'Gamboa Boxing', 'instagram'=>'gamboaboxing', 'website'=>'www.gamboaboxing.com', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Gold Gym', 'nombre_comercial'=>'Gold Gym', 'categoria_id'=>5, 'beneficio'=>'10% Descuento con todas las formas de pago', 'direccion'=>'Edificio World Trade Center, Av. Francisco de Orellana', 'telefono'=>'(04) 263-0917', 'correo'=>'', 'twitter'=>'@goldsgymec', 'facebook'=>'Gold Gym', 'instagram'=>'goldsgymec', 'website'=>'www.goldsgym.com.ec/', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Scienza Body Fit', 'nombre_comercial'=>'Scienza Body Fit', 'categoria_id'=>5, 'beneficio'=>'Por 8 clases recibe 10', 'direccion'=>'Víctor Emilio Estrada # 722 y Guayacanes', 'telefono'=>'099 937 7827', 'correo'=>'', 'twitter'=>'@verticalurdesa', 'facebook'=>'Scienza Body Fit', 'instagram'=>'verticalurdesa_scienzabodyfit', 'website'=>'_', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Alianza Francesa', 'nombre_comercial'=>'Alianza Francesa', 'categoria_id'=>6, 'beneficio'=>'', 'direccion'=>'Hurtado 436 y José Mascote ', 'telefono'=>'(04) 253-2009', 'correo'=>'', 'twitter'=>'@afguayaquil', 'facebook'=>'Alianza Francesa', 'instagram'=>'afguayaquil', 'website'=>'www.alianzafrancesa.org.ec/', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Tecnológico Latinoamericano de Expresiones Artísticas', 'nombre_comercial'=>'Tecnológico Latinoamericano de Expresiones Artísticas', 'categoria_id'=>6, 'beneficio'=>'Matrícula Gratis en carreras o cursos', 'direccion'=>'Edificio Chantal Fontaine, Mz. 1 Solares 10 11, Av Miguel H. Alcívar', 'telefono'=>'(04) 229-6126', 'correo'=>'', 'twitter'=>'_', 'facebook'=>'Tecnológico Latinoamericano de Expresiones Artísticas', 'instagram'=>'lexatec', 'website'=>'www.lexa.edu.ec/', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Hostería SAIANANDA', 'nombre_comercial'=>'Hostería SAIANANDA', 'categoria_id'=>6, 'beneficio'=>'GRATIS desayuno', 'direccion'=>'Km 6.5 - Avenida Sixto Duran Ballen - Bahía de Caráquez', 'telefono'=>'(05) 239-8331', 'correo'=>'', 'twitter'=>'@HotelSaiananda', 'facebook'=>'Hostería SAIANANDA', 'instagram'=>'saiananda', 'website'=>'www.saiananda.com', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Chantal Fontaine', 'nombre_comercial'=>'Chantal Fontaine', 'categoria_id'=>6, 'beneficio'=>'GRATIS 2 Ampliaciones 8R', 'direccion'=>'Edificio Chantal Fontaine, Mz. 1 Solares 10 11, Av Miguel H. Alcívar', 'telefono'=>'(04) 229-6126', 'correo'=>'', 'twitter'=>'@CHANTALFONTAlNE', 'facebook'=>'Chantal Fontaine', 'instagram'=>'chantalfontaine', 'website'=>'www.chantalfontaine.com', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Mi Smart', 'nombre_comercial'=>'Mi Smart', 'categoria_id'=>3, 'beneficio'=>'', 'direccion'=>'Urdesa central calle guayacanes 320B entre la calle 4ta y calle 5ta', 'telefono'=>'(04) 506-2851', 'correo'=>'', 'twitter'=>'@iphone_solucion', 'facebook'=>'_', 'instagram'=>'mismart', 'website'=>'www.instagram.com/mismart', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Frenoseguro', 'nombre_comercial'=>'Frenoseguro', 'categoria_id'=>6, 'beneficio'=>'GRATIS 4ta llanta, alienación y balanceo', 'direccion'=>'Professional Center, av km 2, Av. Juan Tanca Marengo Km 1.5', 'telefono'=>'(04) 500-4500', 'correo'=>'', 'twitter'=>'@Frenoseguro', 'facebook'=>'Frenoseguro', 'instagram'=>'Frenoseguro', 'website'=>'www.frenoseguro.com', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'EcuaDental', 'nombre_comercial'=>'EcuaDental', 'categoria_id'=>7, 'beneficio'=>'40% Descuento en todos los procedimientos ', 'direccion'=>'Ficus entre y, Pte.Victor Emilio Estrada Carmona', 'telefono'=>'(04) 288-0620', 'correo'=>'', 'twitter'=>'@EcuadentalSA', 'facebook'=>'EcuaDental', 'instagram'=>'ecuadental', 'website'=>'www.ecuadental.com', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Grupo Hospitalario Kennedy', 'nombre_comercial'=>'Grupo Hospitalario Kennedy', 'categoria_id'=>7, 'beneficio'=>'10% Descuento en hospitalización ', 'direccion'=>'Cdla Nva Kennedy, Av. del Periodista y Callejón 11', 'telefono'=>'(04) 228-9666', 'correo'=>'', 'twitter'=>'@medicinadehoy', 'facebook'=>'Grupo Hospitalario Kennedy', 'instagram'=>'grupohospitalariokennedy ', 'website'=>'www.hospikennedy.med.ec', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Centro Médico Semedic', 'nombre_comercial'=>'Centro Médico Semedic', 'categoria_id'=>7, 'beneficio'=>'1era consulta GRATIS de odontología', 'direccion'=>'Urd. Circunvalación Sur 905 E/ Higueras e Ilanes', 'telefono'=>'(04) 238-1318', 'correo'=>'', 'twitter'=>'@sumedicoec', 'facebook'=>'Centro Médico Semedic', 'instagram'=>'semedic', 'website'=>'www.semedic.com.ec', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('orden'=>0, 'razon_social'=>'Centro Médico SuMédico', 'nombre_comercial'=>'Centro Médico SuMédico', 'categoria_id'=>7, 'beneficio'=>'', 'direccion'=>'Av. de Las Américas y Abel Romeo Castillo, frente a TC mi Canal', 'telefono'=>'(04) 601-5779', 'correo'=>'', 'twitter'=>'@sumedicoec', 'facebook'=>'Centro Médico SuMédico', 'instagram'=>'sumedico', 'website'=>'www.sumedico.ec', 'tipo'=>'LA', 'ruta_img_small'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/small/', 'ruta_img_large'=>'http://'.config('app.subdomain').'.redlinks.com.ec/img/locales/large/', 'created_at'=>Carbon\Carbon::now()->todatetimestring(),'updated_at'=>Carbon\Carbon::now()->todatetimestring())
		);
		
		DB::table('empresas')->insert($data);
    }
}
