<?php

use Illuminate\Database\Seeder;

class SucursalesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$data = array(
			array('empresa_id'=>1,'orden'=>1, 'nombre'=>'Samborondón', 'direccion'=>'Vía Samborondón C.C. Las Terrazas Local #18 y #19', 'telefono'=>'42838942', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0101', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>1,'orden'=>2, 'nombre'=>'Parque Colón', 'direccion'=>'Parque Empresarial Colón Edif Empresarial 1 local #2', 'telefono'=>'42136574', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0102', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>2,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Victor Emilio Estrada # 722 y Guayacanes', 'telefono'=>'45037923', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0201', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>3,'orden'=>1, 'nombre'=>'Kennedy', 'direccion'=>'Kennedy Norte Av. Luis Orrantia y Nahim Isaías, Torre Médica Udimef 2', 'telefono'=>'42681880', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0301', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>4,'orden'=>1, 'nombre'=>'Samborondón', 'direccion'=>'Km 2.5 Vía a Samborondón CC Plaza Nova 2do Piso Local 5', 'telefono'=>'42838787', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0401', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>5,'orden'=>1, 'nombre'=>'Samborondón', 'direccion'=>'Palmora Plaza Km 18 vía Samborondón', 'telefono'=>'42070798', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0501', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>6,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Urdesa Victor Emilio Estrada junto al Bco. Bolivariano ', 'telefono'=>'098 667 0769', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0601', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>6,'orden'=>2, 'nombre'=>'Mall del Sol', 'direccion'=>'C.C. Sonesta, Av Joaquin Orrantia y Av Tanca Marengo', 'telefono'=>'42638006', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0602', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>7,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Urdesa, Av las monjas 217 y calle 3ra', 'telefono'=>'42382888', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0701', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>7,'orden'=>2, 'nombre'=>'Samborondón', 'direccion'=>'Km 1 1/5 C.C. La Torre, local A-4', 'telefono'=>'42833222', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0702', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>8,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Victor Emilio Estrada 823 e Higueras', 'telefono'=>'46012794', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0801', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>8,'orden'=>2, 'nombre'=>'Sur ', 'direccion'=>'La Saiba Mz Q V No. 34 Entrando Por Kiwi', 'telefono'=>' 42448513', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0802', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>9,'orden'=>1, 'nombre'=>'Samborondón', 'direccion'=>'Vía Samborondón, Km. 2,5 Universidad de Especialidades Espíritu Santo', 'telefono'=>'', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0901', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>9,'orden'=>2, 'nombre'=>'Samborondón', 'direccion'=>'Vía Samborondón, Km. 13,5 Universidad Ecotec', 'telefono'=>'', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK0902', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>10,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Urdesa, Circunvalación 320 y Diagonal esquina', 'telefono'=>'42884630', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1001', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>10,'orden'=>2, 'nombre'=>'Mall del Sol', 'direccion'=>'C.C. Sonesta, Av Joaquin Orrantia y Av Tanca Marengo', 'telefono'=>'42639115', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1002', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>10,'orden'=>3, 'nombre'=>'Ceibos', 'direccion'=>'C.C. Riocentro de los Ceibos, planta alta a lado de B. Bolivariano', 'telefono'=>'42359618', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1003', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>10,'orden'=>4, 'nombre'=>'Centro', 'direccion'=>'Córdova 703 y Junín', 'telefono'=>'42300407', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1004', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>11,'orden'=>1, 'nombre'=>'San Marino', 'direccion'=>'Centro Comercial San Marino, Piso 1 Local 1', 'telefono'=>'097 960 7632', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1101', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>12,'orden'=>1, 'nombre'=>'Mall del Sol', 'direccion'=>'Centro Comercial Mall Del Sol, Piso 1', 'telefono'=>'098 961 6553', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1201', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>12,'orden'=>2, 'nombre'=>'Dorado', 'direccion'=>'C.C El Dorado Planta Baja', 'telefono'=>'4506233', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1202', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>13,'orden'=>1, 'nombre'=>'Citymall', 'direccion'=>'Centro Comercial City Mall, Piso 1', 'telefono'=>'097 879 4022', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1301', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>13,'orden'=>2, 'nombre'=>'Centro', 'direccion'=>'C.C. Malecón 200 Galería C local #32-33', 'telefono'=>'42326851', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1302', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>13,'orden'=>3, 'nombre'=>'El Fortín', 'direccion'=>'C.C. El Fortín Local #250 Planta Alta', 'telefono'=>'', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1303', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>13,'orden'=>4, 'nombre'=>'Durán', 'direccion'=>'Paseo Shopping Durán Local #64 – 65', 'telefono'=>'', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1304', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>13,'orden'=>5, 'nombre'=>'Plaza Mayor', 'direccion'=>'Plaza Mayor Local #13 – 14 – 15 ', 'telefono'=>'42231923', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1305', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>14,'orden'=>1, 'nombre'=>'Servicio Online', 'direccion'=>'Servicio Online a Domicilio', 'telefono'=>'42287453', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1401', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>15,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Calle Bálsamos Sur #201 A, entre calle Única y Todos los Santos', 'telefono'=>'42882785', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1501', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>16,'orden'=>1, 'nombre'=>'Samborondón', 'direccion'=>'Km 6,5 Vía a Samborondón frente a Plaza Lagos', 'telefono'=>'099 950 0682', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1601', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>17,'orden'=>1, 'nombre'=>'Samborondón', 'direccion'=>'Centro Comercial Las Terrazas, Local 2', 'telefono'=>'099 909 2359', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1701', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>18,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Aventura Plaza, Local 17, Av Las Monjas', 'telefono'=>' 42200101', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1801', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>18,'orden'=>2, 'nombre'=>'Samborondón', 'direccion'=>'Edificio del Portal 335 PB, Atrás de Village Plaza', 'telefono'=>'', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1802', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>19,'orden'=>1, 'nombre'=>'Samborondón', 'direccion'=>'Av Rio Esmeraldas, Samborondón', 'telefono'=>'42097447', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK1901', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>20,'orden'=>1, 'nombre'=>'Samborondón', 'direccion'=>'Av. Samborondón Km. 2.5 frente a Plaza Nova', 'telefono'=>'42097078', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2001', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>21,'orden'=>1, 'nombre'=>'Urdenor', 'direccion'=>'Urdenor 1, Mz 130 solares 12 y 13 Av. Francisco de Orellana', 'telefono'=>'46008955', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2101', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>21,'orden'=>2, 'nombre'=>'Puerto Azul ', 'direccion'=>'Puerto Azul, Liga Deportiva Estudiantil, Planta alta', 'telefono'=>'6015861', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2102', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>22,'orden'=>1, 'nombre'=>'Francisco de Orellana', 'direccion'=>'Edificio World Trade Center, Av. Francisco de Orellana', 'telefono'=>'42630917', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2201', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>22,'orden'=>2, 'nombre'=>'Vía a la Costa', 'direccion'=>'Plaza Colonia, tercer piso', 'telefono'=>'', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2202', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>22,'orden'=>3, 'nombre'=>'Universidad Católica', 'direccion'=>'Av. Carlos Julio Arosemena Km. 1/2 vía Daule. Edificio de parqueo, 2do piso.', 'telefono'=>'', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2203', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>23,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Víctor Emilio Estrada # 722 y Guayacanes', 'telefono'=>'099 937 7827', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2301', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>24,'orden'=>1, 'nombre'=>'Centro', 'direccion'=>'Hurtado 436 y José Mascote ', 'telefono'=>'4253-2009', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2401', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>24,'orden'=>2, 'nombre'=>'Urdesa', 'direccion'=>'Bálsamos 202 y Única ', 'telefono'=>'42884483', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2402', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>24,'orden'=>3, 'nombre'=>'Samborondón', 'direccion'=>'Km 3 vía Samborondón ', 'telefono'=>'46010161', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2403', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>25,'orden'=>1, 'nombre'=>'Kennedy', 'direccion'=>'Edificio Chantal Fontaine, Mz. 1 Solares 10 11, Av Miguel H. Alcívar', 'telefono'=>'42296126', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2501', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>26,'orden'=>1, 'nombre'=>'Manabí', 'direccion'=>'Km 6.5 - Avenida Sixto Duran Ballen - Bahía de Caráquez', 'telefono'=>'52398331', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2601', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>27,'orden'=>1, 'nombre'=>'Kennedy', 'direccion'=>'Edificio Chantal Fontaine, Mz. 1 Solares 10 11, Av Miguel H. Alcívar', 'telefono'=>'42296126', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2701', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>28,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Urdesa central calle guayacanes 320B entre la calle 4ta y calle 5ta', 'telefono'=>'45062851', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2801', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>29,'orden'=>1, 'nombre'=>'Tanca Marengo', 'direccion'=>'Professional Center, av km 2, Av. Juan Tanca Marengo Km 1.5', 'telefono'=>'45004500', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2901', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>29,'orden'=>2, 'nombre'=>'Centro', 'direccion'=>'Machala 1200 y Luque (Esq.)', 'telefono'=>'4232 5101', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2902', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>29,'orden'=>3, 'nombre'=>'Sur ', 'direccion'=>'José Vicente Trujillo y Rosa Borja de Icaza', 'telefono'=>'42334 404', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK2903', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>30,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Ficus entre y, Pte.Victor Emilio Estrada Carmona', 'telefono'=>'42880620', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK3001', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>31,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Cdla Nva Kennedy, Av. del Periodista y Callejón 11', 'telefono'=>'42289666', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK3101', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>31,'orden'=>2, 'nombre'=>'Alborada', 'direccion'=>'Calle y Av. Rodolfo Baquerizo Nazur Crotos', 'telefono'=>'42247900', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK3102', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>32,'orden'=>1, 'nombre'=>'Urdesa', 'direccion'=>'Urd. Circunvalación Sur 905 E/ Higueras e Ilanes', 'telefono'=>'42381318', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK3201', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>32,'orden'=>2, 'nombre'=>'Centro', 'direccion'=>'Noguchi 2409 y Bolivia', 'telefono'=>'42445125', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK3202', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>32,'orden'=>3, 'nombre'=>'Sur ', 'direccion'=>'Guasmo Norte, Coop. Río Guayas Mz. 58 Solar 7-8', 'telefono'=>'42050126', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK3203', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>33,'orden'=>1, 'nombre'=>'Mall del Sol', 'direccion'=>'Av. de Las Américas y Abel Romeo Castillo, frente a TC mi Canal', 'telefono'=>'46000110', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK3301', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring()),
			array('empresa_id'=>33,'orden'=>2, 'nombre'=>'Vía a Daule', 'direccion'=>'Parque California 2', 'telefono'=>'46055301', 'longitud_map'=>'', 'latitud_map'=>'', 'qr'=>'RDLNK3302', 'created_at'=>Carbon\Carbon::now()->todatetimestring(), 'updated_at'=>Carbon\Carbon::now()->todatetimestring())
		);
		DB::table('sucursales')->insert($data);
    }
}
